### ISSUE TITLE
The "watch" feature keeps turning off the headlights.

### ISSUE THREAD

**Issue by KannaHayabusa** [blopker/superduper#1]
Continuously switching the riding mode to level 4 seems to disable the headlight after a couple of seconds. Essentially a death sentence when riding in the dark.

**Comment by KannaHayabusa** [comment]
Steps to reproduce: 
1. Turn "watch" on in the app.
2. Turn the headlight on via the display by holding the up button.
3. Within a could of seconds the light will turn off, presumably when switching modes again.

**Comment by blopker** [comment]
Fixed! I think :)

https://github.com/blopker/superduper/releases/tag/0.0.2
