### ISSUE TITLE
High battery consumption 

### ISSUE THREAD

**Issue by JacopoV** [blopker/superduper#10]
Hi there!

Being using more often the app now that's fixed on EU models.
But i started noticing a fairly high battery drain on Android with the lock mode on (i haven't tested while turned off) while never been connected to the bike.

Is there something that can be done? Like ping and check the bike much less if not connected or other solutions?

20% ish of battery consumption seems pretty high.

Here's some screenshots with the app and the battery consumption.

Superduper 0.0.22
Pixel 7 Pro (latest update February 2023)

Thanks 🙏
![Screenshot_20230218-172756](https://user-images.githubusercontent.com/1202954/219877106-80d0cfe1-09ed-43d3-a26c-6887442be425.png)
![Screenshot_20230218-172620-01](https://user-images.githubusercontent.com/1202954/219877120-0cea5fc0-bf3d-404f-99ff-7461fe16815c.jpeg)

**Comment by blopker** [comment]
Hey! While it's expected that having ModeLock on will increase battery usage, I'm surprised it's as much as 10% an hour. ModeLock essentially keeps the phone awake, so it can maintain a connection to the bike. I'll see if there are ways to monitor why it's this much drain and if making some adjustments to how aggressive the app checks for the bike to be there helps.

**Comment by JacopoV** [comment]
Thanks @blopker !

Yeah i m expecting a bit more drain due the nature of the app, but as you mentioned not that much!

I hope you can find some ways to improve it! Thanks 🙏

**Comment by blopker** [comment]
I have no way forward on this, sadly. This seems to be a technical limitation of Android.
