### ISSUE TITLE
Once connected mode keeps going to 1

### ISSUE THREAD

**Issue by Oostelijkeeilanden** [blopker/superduper#13]
Once connected with bluetooth the mode keeps going to 1, can’t change any mode.
On ios iphone 13 pro max

**Comment by blopker** [comment]
Hi 👋!
Do any of the other functions work, like the Light or Assist buttons? Also, I can help better if I get the info in the bug report template: https://github.com/blopker/superduper/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by HSprogress** [comment]
> Once connected with bluetooth the mode keeps going to 1, can’t change any mode.
> On ios iphone 13 pro max

Did you solve your problem??

**Comment by HSprogress** [comment]
> Once connected with bluetooth the mode keeps going to 1, can’t change any mode.
> On ios iphone 13 pro max

Did you solve your problem?? This happens always for me as well. App doesn’t work properly.

**Comment by blopker** [comment]
Sorry to hear that. I'm having trouble replicating the issue though. If you have the steps you take, as detailed as possible, I can try to make it happen myself. Also, make sure you're on the latest version (0.1.1).

**Comment by blopker** [comment]
From @Super73maastricht in #15 :
```
Keep going to mode 1 when using the app.

To Reproduce
Steps to reproduce the behavior:

    Press the bower button on the battery
    Open the app
    You see the mode switching back to mode 1
    Manually have to switch back

Expected behavior
A description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Bike (please complete the following information):

    Model: [e.g. RX]
    Region: [e.g. US]
    Updated Firmware?

Smartphone (please complete the following information):

    Device: [e.g. iPhone6]
    OS: [e.g. iOS8.1]
    Browser [e.g. stock browser, safari]
    Version [e.g. 22]

Additional context
Add any other context about the problem here.
```

**Comment by blopker** [comment]
Also, what region is everyone in, US or EU?

**Comment by Mattlee0034** [comment]
I'm in the US and having a similar issue. Operating off a S20. The bike reverts back to mode 2 (just like the super73 app) once I turn the bike off. Background lock is no but no luck locking mode 4 in.

**Comment by blopker** [comment]
Hm, is there a lock icon next to the Mode text on the Mode button? Background Lock won't do anything unless the settings are locked first by long pressing the corresponding button.

See the lock icons in the image below. 


![Screenshot_20230423-133324.png](https://user-images.githubusercontent.com/757503/233864823-2749fd32-c3b2-41d7-849c-2ea28d87992e.png)

**Comment by DerDarwin** [comment]
So im on iphone15 here. First Ride everything works. After a break, bine went off, the app seem to be connected with the bike but i cant change anything. Everytime i change smthng it switches back to the screen in the picture
![IMG_4131](https://github.com/blopker/superduper/assets/166689820/cade8164-fea2-4224-a6f2-db646f8025a3)

**Comment by Bamuel** [comment]
> So im on iphone15 here. First Ride everything works. After a break, bine went off, the app seem to be connected with the bike but i cant change anything. Everytime i change smthng it switches back to the screen in the picture

I had this similar problem when I sped up the timer to 0.1-1sec. It might be to overlapping Debounce being overwritten.

Adding a cancel to the timer in `void writeStateData` prevents it from being overwritten.
```dart
if (_updateDebounce?.isActive ?? false) _updateDebounce?.cancel();
```
https://github.com/Bamuel/superduper/blob/6074c477ec89644029bb3a14d5f29c26f20b567c/lib/bike.dart#L84

Not sure why a fresh restart and a new iPhone this weird magic occurs.
@DerDarwin Is the distance from your phone to bike far? or do you have a heavy phone case?

**Comment by DerDarwin** [comment]
> > So im on iphone15 here. First Ride everything works. After a break, bine went off, the app seem to be connected with the bike but i cant change anything. Everytime i change smthng it switches back to the screen in the picture
> 
> I had this similar problem when I sped up the timer to 0.1-1sec. It might be to overlapping Debounce being overwritten.
> 
> Adding a cancel to the timer in `void writeStateData` prevents it from being overwritten.
> 
> ```dart
> if (_updateDebounce?.isActive ?? false) _updateDebounce?.cancel();
> ```
> 
> https://github.com/Bamuel/superduper/blob/6074c477ec89644029bb3a14d5f29c26f20b567c/lib/bike.dart#L84
> 
> Not sure why a fresh restart and a new iPhone this weird magic occurs. @DerDarwin Is the distance from your phone to bike far? or do you have a heavy phone case?

Im sitting on top of the bike. No Phone Case No Screenshield. In a Linen Trouser 😁 The App see the Bike, i can press on it, get to the screen as you see in the pic, thats all i can do for now :(

**Comment by blopker** [comment]
There's been a bunch of stability updates since this ticket was created. Please try the newest version! Other fixes: make sure the bike is on the newest firmware, make sure no other apps are connected to the bike by restarting your phone and only using SD.

**Comment by DerDarwin** [comment]
I fixed it with the Official Super73 app!If my bike dont connect with superduper i just vonnect to the official app, open the superduper get connected with it and. Close the official app again then it works Gesendet mit der GMX iPhone AppAm 28.06.24 um 20:12 schrieb Bo Lopker
                
            
            
                
                    Von: "Bo Lopker" ***@***.***>Datum: 28. Juni 2024An: "blopker/superduper" ***@***.***>Cc: "Mention" ***@***.***>,"DerDarwin" ***@***.***>Betreff: Re: [blopker/superduper] Once connected mode keeps going to 1 (Issue #13)
                
                
There's been a bunch of stability updates since this ticket was created. Please try the newest version! Other fixes: make sure the bike is on the newest firmware, make sure no other apps are connected to the bike by restarting your phone and only using SD.
