### ISSUE TITLE
Once connected mode goes to 1 even in background lock

### ISSUE THREAD

**Issue by Super73maastricht** [blopker/superduper#15]
Keep going to mode 1 when using the app.

**To Reproduce**
1. Press the bower button on the battery
2. Open the app
3. You see the mode switching back to mode 1
4. Manually have to switch back

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Bike (please complete the following information):**
 - Model: [e.g. RX]
 - Region: [e.g. US]
 - Updated Firmware?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blopker** [comment]
Hey! Thanks for the detailed info. There's already a ticket for this, so I'm going to copy this over to that one to merge them.

**Comment by blopker** [comment]
Merged with #13
