### ISSUE TITLE
Functionality suggestion

### ISSUE THREAD

**Issue by sinneD1988** [blopker/superduper#17]
Hi,

First off my compliments on the app, very nice and easy to use!

I’ve read through some of the history and I believe that it has been possible to enable throttle assist on different modes these bikes have? At least from what I understood it was accidentally enabled/disabled on some previous versions of this app?

Would be a very nice feature if it would be possible to toggle throttle assist manually for each of the modes the bike has!

Kind regards,

Dennis

**Comment by blopker** [comment]
Thanks! I'm glad you've found the app useful. My guess is that previous versions assumed all bikes were in the US. US and EU have different meanings between the modes, especially as it relates to throttle assist. This wasn't removed, rather EU support was added. However, if the app incorrectly detects the bike region, you can always switch regions in the Edit menu (where you can also change the bike name).

Hopefully that helps?

**Comment by sinneD1988** [comment]
I found the region settings, just to clarify, would setting the region to US then give the EU bikes throttle assist at lower modes?

**Comment by blopker** [comment]
From the official app, here's what it says about the differences in the two regions (PAS is Pedal Assist):
```
US:
- 1: Class 1 - PAS Only, 20 mph
- 2: Class 2 - PAS & Throttle, 20 mph
- 3: Class 3 - PAS Only, 28 mph
- 4: OFF-ROAD - PAS & Throttle, no limit

EU:
- 1: EPAC - PAS, 25 km/h
- 2: 250W - PAS, 35 km/h
- 3: 850W - PAS, 45 km/h
- 4: OFF-ROAD - PAS/Throttle, no limit
```
On my bike, which is set to US, the throttle works on all modes. I haven't tried really riding the bike in EU mode though. As for what will happen with your particular bike? I can't be sure. If you try it, I'd love to know what happens.

**Comment by Mattlee0034** [comment]
K6

**Comment by sinneD1988** [comment]
Sorry for my late reply. Got to test the bike with both US and EU region settings but they don’t make any difference.

So for an EU bike you don’t get the throttle assist as it seems.

**Comment by blopker** [comment]
Huh, thanks for the info. I do know the region doesn't actually switch until you change the mode as well. So, flip the region, then tap the mode button to change the mode number. That triggers the app to actually update the mode on the bike. If you get a chance to try that again, let me know!
