### ISSUE TITLE
Superduper is not able to keep the good settings (mode 4)

### ISSUE THREAD

**Issue by ovnis82** [blopker/superduper#19]
Hi !

Randomley, my RX 73 (EU) reverts back to mode 1 once I turn the bike off.  And it's not able to connect to my super 73. 

I have tested this one with two differents android smartphone. 

Background lock is enabled. 

Controler version 206
BLE version 221122

Thx for the help!

**Comment by blopker** [comment]
Hey! Background Lock isn't always rock solid on some phones. If you list the phones you tried here we can star to figure out which ones have problems. The main issue is that the phones like to shut off apps, even if the app requests not to be shut down. Typically opening the app will get everything working again.

**Comment by ovnis82** [comment]
It seems to solve my issue with energy saving "disabled" (inside android parameters) for superduper. But I have to make more tests. 
 
 It would be great to add one thing to your great and necessary application:

-  The ability to set what time the bike lights start and stop

**Comment by ovnis82** [comment]
When I ask to super duper to run automatically at android startup, it doesn't change bike setting if don't go to the application. Any idea?

**Comment by blopker** [comment]
Like, when the phone restarts? You will need to open the app again after
every phone restart since Android kills all the running background
processes when it shuts down. Opening the app again will start the
background process again.

**Comment by ovnis82** [comment]
Hi, maybe putting it as a system task would solve this problem of an application which which closes by itself or malfunctions?

With the auto start, we shouldn't even worry about launching it when the laptop starts up!

**Comment by blopker** [comment]
Auto starting is out of scope now due to technical limitations. Hopefully this will change in the future, but there's no way forward for now.
