### ISSUE TITLE
Support E-Twow Scooters

### ISSUE THREAD

**Issue by eqqe** [blopker/superduper#21]
The E-Twow Scooters can also connect via Bluetooth Low Energy (ble) and will be exposing and writing characteristics.

I would be available to add the connectivity options like in my other repository https://github.com/eqqe/etwowconnect2 but getting the benefits of your application.

**Comment by blopker** [comment]
Hey, thanks for the idea, but other brands are out of scope for this project. You're more than welcome to fork this and add support though!
