### ISSUE TITLE
Appreciation and FW Question

### ISSUE THREAD

**Issue by dylanprins** [blopker/superduper#22]
First of all, thank you so much for writing this app. Second, is it possible to update the bike to the latest FW? I did not update as of yet because i was scared to lose my off road mode. Today they seemed to have bricked the bike again in the s73 app. Maybe they also updated the FW so it blocks your app. I want to update the FW so i can get the torque update.

**Comment by blopker** [comment]
Hey! Thanks for the kind words. I have not yet heard of any reports of people not being able to use SD on the newest bike firmware (the torque update). This could always change though with an even new update. I have not heard of any newer updates coming out though. If one does come out, and it breaks SD, I'll definitely investigate how to get SD working again :).
