### ISSUE TITLE
Feedback & Feature Request (Show current Speeds & Voltage Usage & Battery Level)

### ISSUE THREAD

**Issue by Bamuel** [blopker/superduper#24]
Hi, 
Just used the amazing app on my
Consistent Piranha (Bike Name) on my EU bike here in Australia. 
Which is amazing with the way the bike feels completely new with the EU -> US transition (stronger acceleration/PAS ).

However since the swap from the official app to the super duper app, I noticed its missing Current Speed & Current Battery & Current Voltage/Watts Use. Was wonder if we can keep it on the main screen.
Extra points if you can make it detect indicators.

**Comment by AxelFougues** [comment]
Speed and other metrics are totally possible, here is the wiki for those @blopker if you need reference: https://github.com/AxelFougues/Walker73/wiki
I haven't found anything about the indicators but I do have the walk assist and some other values are still unidentified so maybe...

**Comment by blopker** [comment]
Like @AxelFougues said, I generally like to keep the app light. If you're on Android the Walker73 has more of a dashboard experience you might like. Although since this is the first time someone has actually asked for this info, I', curious how you would use it. Do you mount your phone on your bike? Just like to check the levels when you're not riding?

**Comment by Bamuel** [comment]
I'm using iPhone, so its a bit bias. 

1. Personally when riding phone is mounted on center. Normally I have Spotify (music) player showing. However I scroll between apps to check Bike Battery Percentage when doing bigger rides on red lights/breaks, ensuring I have enough range.

2. Emailed privately.

However I am fine with/without the feature request. (It was only a suggestion)

**Comment by blopker** [comment]
Thanks for the extra context, and for the request! I'll leave this up for now in case anyone wants to add a +1. I'm curious though, does your bike not have the bar mounted circle screen? I typically use that for the battery indicator.

**Comment by Bamuel** [comment]
My bike has the diamond screen, and to see the battery is the circle on the border.
However its very hard to tell the percentage, especially when its not 25%, 50%, 75%, 100%
eg. 64% of a circle is very hard to read accurately.

**Comment by AxelFougues** [comment]
> My bike has the diamond screen, and to see the battery is the circle on the border. However it's very hard to tell the percentage, especially when its not 25%, 50%, 75%, 100% eg. 64% of a circle is very hard to read accurately.

100% agree with this, the recessed screen makes the border ring very hard to see unless you're facing it perfectly.

**Comment by blopker** [comment]
Great. Thanks for the info. @AxelFougues, can you point to the code in Walker to get the battery level? What math is required to map the raw values from 0 to 100 percent?

**Comment by AxelFougues** [comment]
> Great. Thanks for the info. @AxelFougues, can you point to the code in Walker to get the battery level? What math is required to map the raw values from 0 to 100 percent?

Receiving the data bytes here: 
https://github.com/AxelFougues/Walker73/blob/c94772aabb0587332c3efd997ac0ab58eb145826/Assets/BikeState.cs#L300

I then extrapolate the battery level from the range:
https://github.com/AxelFougues/Walker73/blob/c94772aabb0587332c3efd997ac0ab58eb145826/Assets/BikeState.cs#L323

And then I approximate the voltage from the level using a standard Li-ion discharge curve 😉

**Comment by AxelFougues** [comment]
Here is a good reference for Li-ion % to V correspondence. Their sheets are very convenient:
https://talesontwowheels.com/2019/10/02/li-ion-ebike-battery-charge-charts/?amp=1

**Comment by blopker** [comment]
Amazing, thank you. This will make it easier to implment.

**Comment by Bamuel** [comment]
I am very interested to learn dart & flutter as I normally code heavy in php and want to try something new.

If you haven't started. Will do a pull request in the future with the the changes.

**Comment by blopker** [comment]
Definitely! I find Flutter to be the best mobile development experience at this point. The challenge with this project is that it's hard to use an emulator to test since most of the functions need Bluetooth. Happy to answer any questions though.

**Comment by Bamuel** [comment]
Made some progress, Now I have carry my heavy bike from garage into my apartment to continue the live testing (with a dummy android with Bluetooth), also never wiresharked a Bluetooth connection, so I'll give that an attempt to get more of a better knowledge of the bike.

https://github.com/blopker/superduper/compare/main...Bamuel:superduper:main

![image](https://github.com/blopker/superduper/assets/6744113/68dffad5-7f48-409a-a644-2f63ba20a20c)

**Comment by blopker** [comment]
Looks good! Yeah, I had to move my bike out of my living room after the girlfriend started making remarks :)

**Comment by Bamuel** [comment]
@blopker 
Having the same problem with GF not allowing me to keep the bike upstairs/living room (while she is home), but to confirm am I going to the right path
https://github.com/blopker/superduper/blob/8beb955abf535937ac82075e2d8acb40cc7b9aef/lib/repository.dart#L145C21-L145C42
`getNotificationStream(String deviceId)` 
*Not used anywhere in the code?

I think this returns the bike's data for me to get the Bike info. 

@AxelFougues I am assuming you are getting the battery estimated based of the range?
What is the difference between UUID_CHARACTERISTIC_REGISTER & UUID_CHARACTERISTIC_REGISTER_NOTIFIER, 
Does it matter where I get my data from?

**Comment by blopker** [comment]
Right `getNotificationStream` isn't used right now. The app polls the bike currently instead of using a subscription. When I tried to do a sub it was a bit unstable, but I didn't try that hard. If you do get that working reliably it would be a great improvement.

**Comment by blopker** [comment]
Polling is kicked off here: https://github.com/blopker/superduper/blob/8beb955abf535937ac82075e2d8acb40cc7b9aef/lib/bike.dart#L33C1-L35C8

**Comment by Bamuel** [comment]
Thanks everyone for the guide.
Makes a lot more sense now.

> You can use UUID_CHARACTERISTIC_REGISTER at any time to read any data. First you need to choose what data you want by writing the id to UUID_CHARACTERISTIC_REGISTER_ID and then read at UUID_CHARACTERISTIC_REGISTER.

Then I will use readCurrentState() which does above mentioned.

> Polling is kicked off here: https://github.com/blopker/superduper/blob/8beb955abf535937ac82075e2d8acb40cc7b9aef/lib/bike.dart#L33C1-L35C8

Awesome 😄

**Comment by Bamuel** [comment]
I got it to work, Thanks everyone, Will do a pull request soon.
<img src='https://github.com/blopker/superduper/assets/6744113/dc972ff3-bfbc-4582-a5e8-3e85651b9c68' height='800'>

**Comment by blopker** [comment]
Nice! Is it possible to have the battery icon roughly reflect the state of charge? i.e. Full battery icon at 80-100%, then lower as the percentage goes down? Having a full battery with a not full icon would kill my OCD 😄

**Comment by Bamuel** [comment]
> Nice! Is it possible to have the battery icon roughly reflect the state of charge? i.e. Full battery icon at 80-100%, then lower as the percentage goes down? Having a full battery with a not full icon would kill my OCD 😄

That's already done, *It an old screenshot

But i done the calculation based on eye
![image](https://github.com/blopker/superduper/assets/6744113/bb11d8f1-f3d8-4505-b06e-657dae4fac94)

**Comment by blopker** [comment]
Awesome! It's cool you get the icon in your sidebar there. I'm not sure mine does that.

**Comment by blopker** [comment]
Also, there's an opportunity here to use the `switch` expression:

```dart
String getBatteryLevelIcon(int batteryLevel) {
  return switch (batteryLevel) {
    > 95 => "case 0",
    > 80 => "case 1",
    > 50 => "case 2",
    > 20 => "case 3",
    >= 0 => "case 4",
    _ => "default",
  };
}
```

Maybe a little easier on the eyes :)

**Comment by Bamuel** [comment]
> Awesome! It's cool you get the icon in your sidebar there. I'm not sure mine does that.

I changed widget.dart to do that. It makes things look better, especially for people who don't read English as their main language.




> Also, there's an opportunity here to use the `switch` expression:
> 
> ```dart
> String getBatteryLevelIcon(int batteryLevel) {
>   return switch (batteryLevel) {
>     > 95 => "case 0",
>     > 80 => "case 1",
>     > 50 => "case 2",
>     > 20 => "case 3",
>     >= 0 => "case 4",
>     _ => "default",
>   };
> }
> ```
> 
> Maybe a little easier on the eyes :)

Sure. Easy, update.
I tend to avoid switch, as I've  seen multiple occurrences of switch statements (at work) reach over 1000 lines, and its nasty, especially if you want to edit it.

**Comment by Bamuel** [comment]
https://github.com/blopker/superduper/pull/25
