### ISSUE TITLE
*QUESTION* regarding "making the bike faster"

### ISSUE THREAD

**Issue by RipppX** [blopker/superduper#33]
I am looking to buy a super73 and I am in EU. You mention that the app can only do what is already built into the official app... But from my understanding the EU versions (specifically Sweden) cannot be put into unlimited/throttle/offroad mode where it goes faster than 25 km/h in the official app...? 

Does this mean that the superduper app wont be able to do that either? 

Just want to make sure I can go faster than 25 km/h when spending 2000 EUR...
Also new here so didnt know where to ask questions.

**Comment by AxelFougues** [comment]
The settings for different modes are hidden in the official app based on your location and bike model. The bike itself is not locked, they are all the same bikes really. 
Our apps show all the settings so you can switch to any US or EU mode.
(I believe superduper has US modes, walker73 has EU and US)
Here is a list of the modes with the speeds:
https://sites.google.com/view/super73-reverse-engineering/documentation?authuser=0#h.lne9cvtdnbbp

**Comment by RipppX** [comment]
I see, thanks for the quick reply! 

You don't by any chance know if all models (EU and US) have the loose connector for throttle upgrade or is that exclusive to US?

**Comment by AxelFougues** [comment]
Throttles are not allowed on the street but it's perfectly legal to use one on private property so they wouldn't remove the connector.

They should all have it. In fact S73 sells "offroad" kits with throttles and different handle bars both in the EU and US and make it very clear that they are for private property only.

**Comment by RipppX** [comment]
I cant seem to find those kits on their official website, only third party websites. However they do look oem like you say, however they also all say that they are only compatible with certain models... (S2, RX och ZX) that could however be in regards to the handlebar and not the throttle. Once again thank you for replying :)

**Comment by AxelFougues** [comment]
Yeah probably different connectors and handlebars on the older modes.

**Comment by Bamuel** [comment]
Hi @RipppX 

The Super73 is basically capped to 25km/h for legal reasons (in EU)
If your bike is the model S2, RX, ZX models, you are able to use SuperDuper app or the Super73 official app.
The throttle should be an optional add-on when purchasing the e-bike, which I highly recommend getting it. 
_You can proceed without it, but then you are purely relying on Pedal Assists to get you past 25km/h_

Within both apps, there are settings where you can change it to go faster than 25km/h
![image](https://github.com/blopker/superduper/assets/6744113/b5e36497-94c3-4caa-bd19-5adda765f0f7)


Other models of the Super73 which are considered out-dated (slower). Some have throttles, but is only capped by it's motor compacity and don't have any Bluetooth settings.

**Comment by AxelFougues** [comment]
If you don't want the handlebars, you can get the same throttle on AliExpress or amazon for a few bucks btw, don't get ripped off, it's a standard widespread connector. 😉

@Bamuel I get notifications for your issues and unsubscribing doesn't seem to be working so I guess I'll keep lurking around  😂😂

**Comment by blopker** [comment]
Thanks guys!
