### ISSUE TITLE
Connected but couldn’t change the speed

### ISSUE THREAD

**Issue by Esfadiar** [blopker/superduper#34]
Hey, I recently bought a super73 zx-e storm grey. Its the version they don’t make anymore. I cant change the mode on the official super73 app so i found out there was this app super duper. Well I downloaded it and i could connect with my bike but I couldn’t turn on the lights or go any faster. Is it just me or am I missing something?

**Comment by Bamuel** [comment]
I @Esfadiar,

So in the official app, you can change the bike speed, by going settings->bike (set to mode 4).
SuperDuper app just makes it quicker/easier.
![image](https://github.com/blopker/superduper/assets/6744113/0fccf260-6ee7-45c0-82f8-82c6319a5e4f)

But it is strange how you could not toggle the lights/mode via the app.
Have you tried using the official app to update your e-bike?

**Comment by Esfadiar** [comment]
@Bamuel The thing is i set it to all the modes possible on superduper but every single one of them didn't give me more than 25 kph and i have updated the bike on the newest version so yeah. If you cab help let me know

**Comment by Esfadiar** [comment]
@AxelFougues Yeah i know i does really sound like am not connected but there only appears 1 bike when turning my super on and when i turn my bike off I can't connect anymore( which is normal) so I really don't know what to do

**Comment by Esfadiar** [comment]
Is the walker app on ios as well? Is there a way i can find the problem or maybe reset the whole bike?

**Comment by AxelFougues** [comment]
Nah it's not, I was too lazy to port it over and also super duper was already on ios so it wasn't necessary 😅

I don't think you can do much to the bike other than checking for an update with the official app. Maybe remove the battery for a few minutes?

You can use an app like nRF ( a Bluetooth sniffer) to get a bunch of info about the bikes Bluetooth coms which would be helpful for us to see if something is different from other bikes:
https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp
I don't know if this specific one is on ios but I'm sure there are similar ones

**Comment by Esfadiar** [comment]
![image](https://github.com/blopker/superduper/assets/171146141/8ff4c490-7e80-4e71-a5db-0c0cb7dc9ad7)
Don't know what this means or does but i just want to make sure this hasn't something to do with the problem

**Comment by Esfadiar** [comment]
![image](https://github.com/blopker/superduper/assets/171146141/3add456a-94b5-4e9f-9c7c-ad3435a0c912)
Don't know if this helps you guys again just making sure

**Comment by Esfadiar** [comment]
Guys it's finally working!!! Thanks for the help😁 really appreciate it!!

**Comment by AxelFougues** [comment]
> Guys it's finally working!!! Thanks for the help😁 really appreciate it!!

What did you do?

**Comment by Esfadiar** [comment]
Delete the app and took the battery out for a few minutes and then reinstall the app and everything works now

**Comment by blopker** [comment]
Glad you got it working!
