### ISSUE TITLE
Request to Permanently Unlock Mode 4 and Enable "LOCK" Feature on iOS

### ISSUE THREAD

**Issue by Denys06** [blopker/superduper#35]
Hi Team,

I would like to request the ability to permanently unlock Mode 4 on my Super73 bike so that it remains active every time I start the bike.

I have installed your application on iOS using TestFlight. I noticed that I do not have access to the "LOCK" mode, which allows the settings to be saved permanently. Is this expected behavior?

Could you please add this feature to the iOS version of the app? Unfortunately, I do not have an Android phone. While I have several Android devices, the Superduper app is not available for download in their respective app stores.

Thank you for your assistance!
Best regards,
Denys

**Comment by blopker** [comment]
Hey! Yes, unfortunately Apple does not allow this function to work the same way it works on Android. This actually happens a lot with Apple.

**Comment by Denys06** [comment]
Thank you for your quick response.
I am frantically searching for a way to achieve what I want with my bike.

Is there a solution using your app to reprogram the bike's firmware and keep mode 4 activated all the time without draining the battery (even on Android)?

Alternatively, do you know if there is another way to reprogram the firmware to keep it as original but with mode 4 always activated? This is my preference since I only ride on dirt trails.

If there is no solution, I will look for a friend with an Android phone. However, the fact that it drains the battery when stationary is a bit concerning for me.

**Comment by blopker** [comment]
While this app makes it much more convenient to set the mode, just open the app with the bike on, there's currently no permanent solution. 

If you do find a way to modify the bike firmware, please let us know!

**Comment by Bamuel** [comment]
The Super73 are locked to mode 1 on boot, this most likely due to legal issues. I doubt Super73 will push a firmware update which will save the modes.

In the meanwhile, use SuperDuper as its pretty fast to connect and set to mode 4.

**Comment by Denys06** [comment]
For my part, I use my bike only in nature and I do not wish to carry a mobile phone with me when I use it.

Therefore, I am still looking for a permanent solution that does not require a phone. If you have a solution, even in a few months, please respond to this topic as it would be very helpful. Thank!

**Comment by Bamuel** [comment]
> For my part, I use my bike only in nature and I do not wish to carry a mobile phone with me when I use it.
> 
> Therefore, I am still looking for a permanent solution that does not require a phone. If you have a solution, even in a few months, please respond to this topic as it would be very helpful. Thank!

You can find custom Super73 controllers online, but it requires some technical know-how. Be sure to research and proceed carefully as it makes your bike not super73 (but with Super73 parts).

If a better solution becomes available in the future, I'll let you know.

**Comment by blopker** [comment]
So yeah, this request is out of scope for SD for now.
