### ISSUE TITLE
Connected but changing modes won’t work

### ISSUE THREAD

**Issue by rasmusbk** [blopker/superduper#39]
Hi,

The very first time I connected my super73 to the app, everything worked fine. But as soon as I started the bike 30 minutes later it stopped working. 

Status: The bike connects easily, but when I tap the buttons to change the mode to “mode 4“ it drops back to Mode 1. Same with the light - the app is connected but it’s impossibke to make a change.

Anyone any idea of what the problem is?

Ps. I'm using Iphone 14, newest software. 

Cheers

**Comment by Bamuel** [comment]
Hey @rasmusbk 

I haven't encountered this issue yet. 

But try turning off Background App Refresh on the official Super73 app/
Settings -> Super73 -> Background App Refresh 

Let me know if that works!

**Comment by rasmusbk** [comment]
HeyThank you, I updated the Super73 software and now it runs perfectly. Thank you so much for creating this app. Have a good oneCheersKind Regards,Rasmus KongsørePhotographerTel. +47 936 130 29kongsore.comOn 24 Jun 2024, at 03:01, Samuel ***@***.***> wrote:﻿
Hey @rasmusbk
I haven't encountered this issue yet.
But try turning off Background App Refresh on the official Super73 app/
Settings -> Super73 -> Background App Refresh
Let me know if that works!

**Comment by blopker** [comment]
Thank you!
