### ISSUE TITLE
Assist not working?

### ISSUE THREAD

**Issue by Syb3rnetix** [blopker/superduper#4]
Issue description: After connecting and selecting mode 3 and assist level 4 the throttle works but assist is not, as if it’s still on level 0. Changing the assist on the phone or the  controller screen still does not apply assist correctly. After connecting using the Super73 app it works again.

Bike: Super73 S2 EU
Controller version: 410
Phone: iPhone 13
Operating System: iOS 16.1.2
App version: 0.0.13

**Comment by blopker** [comment]
Hey! I was worried that different models might have different commands. It sounds like only the Assist button doesn't work? I'm surprised the on bike screen also seems to break when you try it? I'm not sure how to fix this though since I don't own an S2. I'll need to think about how to get the information I need.

**Comment by Syb3rnetix** [comment]
The controller has S2 written on it. Mine specifically is "SUPER73_S2_EU_V204". I assume you use some kit to capture the bluetooth signal being sent from the phone to the controller?

**Comment by blopker** [comment]
Yes, if you're up for it, I used https://www.synapse.com/bluesee/ to connect to the bike to have control over the signals sent to it. I also was able to get the debug logs off the official Android app using Android Studio. The logs show the exact data each command sends. I would then send the commands with BlueSee and change them to see what happens.

**Comment by Syb3rnetix** [comment]
Happy to try. Wuld be interesting to see if anyone else with a S2 or a ZX are experiencing the same issues.

**Comment by blopker** [comment]
That good info. I'm going to close this as a dupe for #6. It looks like the general issue is that the S2 model needs to be supported.
