### ISSUE TITLE
Selection not working and come back to initial value

### ISSUE THREAD

**Issue by Alexntf** [blopker/superduper#43]
**Describe the bug**
Bike connected by mode, assists and light not working 

The bike is written as connected but when I want to turn on the light or change mode : it is selected then comeback to initial value. 

**To Reproduce**
1. Go to 'bike scren '
2. Tap on 'mode' 
3. The mode is activated 
4. Then 2-3 seconds after it s unselected 

**Expected behavior**
The selection should stay : if I want to upgrade the mode from 1 to 2, it should stay at 2.  And not come back to 1

**Screenshots**
I do not have the right screen but I can upload a rec screen 
![image](https://github.com/user-attachments/assets/b5de8ffe-35be-4772-a6d2-15da450957a2)

**Bike (please complete the following information):**
 - Model: S adventure 
 - Region: I tried both 
 - Updated do not know but I bought my bike 4 days ago 

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 17.5.1
 - Browser safari 
 - Version do not know 

**Additional context**

**Comment by blopker** [comment]
Hi! Sorry the app is having issues. It sounds like the bike firmware may not be up to date, that or the official app is still connected to the bike causing a conflict.

Did you try following the FAQ? https://github.com/blopker/superduper?tab=readme-ov-file#the-app-wont-connect-to-my-bike

**Comment by Alexntf** [comment]
Really strange because finaly it worked. But I had to delete the bike from my bluetooth devices and be connected to the officiel app. 

(Tomorow morning I will try again and see what happens) 

May you give me the link of the s73 Discord ? 

Thank you mate !

**Comment by Alexntf** [comment]
How can I see my bike firmware?

**Comment by blopker** [comment]
Discord: https://discord.com/invite/DgXTumF 😊

**Comment by Cheesygremlin7** [comment]
I have the same issue now, no idea how to fix it. Strange because the app worked an hour ago…

**Comment by Alexntf** [comment]
> I have the same issue now, no idea how to fix it. Strange because the app worked an hour ago…

Hey @Cheesygremlin7 , I found technics that works 90% of time 
1. Open SuperDupper app at the same time, even before you turn on the battery 
2. If it's not working, go on off super73 app, wait that it's connected, then come back to SuperDuper and exit official app from the multitask ! 

Hope it's gonna work for you

**Comment by Cheesygremlin7** [comment]
Hey! Yeah this worked, thanks :)
