### ISSUE TITLE
Hi can anybody help me out, just bought a new 73 since my old one was defect. I upgraded the model from ZX to S2 to only realize that the speed is very slow and not even worth all the money I spend on this bike! I have downloaded the TestFlight app did everything the right way. Connected my bike but it doesn’t seem to work, if I change the light or speed it doesn’t go over to my bike, can anybody please help me? EU

### ISSUE THREAD

**Issue by MaysaS2** [blopker/superduper#45]

**Comment by blopker** [comment]
Hey! Sorry the app gave you issues. Would you be open to commenting the fix you found so others can learn? Thanks!

**Comment by MXMs2** [comment]
Hi, no problem! I read in one of the comments that the bike probably needed a firmware update if the connection with SuperDuper and S73 was unresponsive. I did this through the official S73 app. Then, I turned the battery on and off, disconnected the S73 app, and reconnected with the SuperDuper app. After that, the app worked in connection with the bike. Super great and thanks for your response!

**Comment by blopker** [comment]
Perfect, thank you!
