### ISSUE TITLE
TestFlight iOS app has expired

### ISSUE THREAD

**Issue by Cheesygremlin7** [blopker/superduper#49]
Hey! Did you use the link on the readme? You shouldn't need a code: https://testflight.apple.com/join/Tl0UibRY

_Originally posted by @blopker in https://github.com/blopker/superduper/issues/48#issuecomment-2303070643_

**Comment by Cheesygremlin7** [comment]
Using this link doesn’t work - it says the “beta isn’t accepting any new testers right now”. Is there another way to reactive the app after the previous version expried?

**Comment by Trengo18** [comment]
I have the same issue on IOS

**Comment by blopker** [comment]
Hello! It looks like Apple took the app down. I'm working on getting it back up, but I'm in Bali and the Internet is spotty. Hold tight!

**Comment by blopker** [comment]
Alright, sent the new build in for review. The fate of the app is in Apple's hands now. If the app is approved, we should be fixed in <24 hours.

**Comment by Cheesygremlin7** [comment]
Thanks Bo!

**Comment by volkancaliskan** [comment]
Thank you so much! 🍀

**Comment by Trengo18** [comment]
Thanks ! 🙏

**Comment by chinitotuchman** [comment]
Thanks bo! Came here to comment the same thing 🙏🏼

**Comment by Cheesygremlin7** [comment]
It's available on IOS again! Thanks Bo!

**Comment by Cheesygremlin7** [comment]
Hey Bolopker, the same issue has come again - IOS TestFlight not accepting new testers right now. Can you renew it again?

**Comment by blopker** [comment]
Thanks for the poke! I've uploaded a new version. It should be live within 24 hours.
