### ISSUE TITLE
The beta version is out of date

### ISSUE THREAD

**Issue by Trengo18** [blopker/superduper#50]
Hi, 

I hope you are going well.

I was trying the app on IOS and I have the message the beta version is over. How can I continue to used it ? 

Can we install it back ?

**Comment by blopker** [comment]
Hello! It looks like Apple took the app down. I'm working on getting it back up, but I'm in Bali and the Internet is spotty. Hold tight!

**Comment by blopker** [comment]
Duplicate: https://github.com/blopker/superduper/issues/49
