### ISSUE TITLE
The app says its beta phase has ended and doesnt accept me in back

### ISSUE THREAD

**Issue by FreakBobbb** [blopker/superduper#51]
Wanted to open the app to go out driving seems like theres a issue with the app hopefully it gets solved quickly

**Comment by blopker** [comment]
Hello! It looks like Apple took the app down. I'm working on getting it back up, but I'm in Bali and the Internet is spotty. Hold tight!

**Comment by blopker** [comment]
Duplicate: https://github.com/blopker/superduper/issues/49
