### ISSUE TITLE
Suggestions news ideas 

### ISSUE THREAD

**Issue by Trengo18** [blopker/superduper#54]
Hi,

First of all thank you so much for the app. 

I want to know if it is possible to put the level of the battery on the app ? 

Second question, is it possible to put a button to have the throttle in mode 1-2-3 ? Like a button Throttle On / Off ? 

I wish you a good day !

**Comment by blopker** [comment]
Hey! It is possible to show the battery level and I think @Bamuel is exploring options there, however, there's no ETA on that since I wouldn't use it myself.

On the second question, I'm not sure that I understand. Are you looking for a physical button to put on your handlebars?

**Comment by Trengo18** [comment]
Hey !

thank you for your reply and your work.

I bought a button to speed it up. I wanted to know if it was possible to have a button on the Superduper that would allow us to activate it in any mode.

**Comment by blopker** [comment]
I'm sorry, I'm still not understanding. However, there is no way to connect a physical button to the Superduper app right now.

**Comment by Trengo18** [comment]
Ok no problem. Thank you for the answers :)
