### ISSUE TITLE
Same issue has come again - IOS TestFlight not accepting new testers right now.

### ISSUE THREAD

**Issue by Cheesygremlin7** [blopker/superduper#57]
Hey Bolopker, the same issue has come again - IOS TestFlight not accepting new testers right now. Can you renew it again?

_Originally posted by @Cheesygremlin7 in https://github.com/blopker/superduper/issues/49#issuecomment-2561864630_

**Comment by blopker** [comment]
Oops, thanks for letting me know! I wish they would email me or something before they did this. Oh well.

Pushing a new version now. It should be live within 24 hours.
