### ISSUE TITLE
Bike is not discoverable.

### ISSUE THREAD

**Issue by louisber7** [blopker/superduper#58]
Hello, I bought this Bike (2022 Super 73 ZX) preowned and can’t connect to either app. Previous owner unpaired the bike but still no luck. This bike doesn’t come with a display so I am wondering if there is another way to make the bike discoverable as I cannot find it in each app.

if you have any tips would be greatly appreciated!

**Comment by blopker** [comment]
Heya, the display is what is making the connection. Without that the bike will not have the Bluetooth hardware needed.

**Comment by louisber7** [comment]
Aw. That makes sense thank you for the help. It’s weird though, from what I understand the 2022 Super 73 ZX did not come with a display? Does that mean it was never able to connect to the app. I guess I will be adding a display. 
Thank you so much for your help, super 73 themselves have been a nightmare. 


Sent from Yahoo Mail for iPhone


On Friday, December 27, 2024, 11:55 AM, Bo Lopker ***@***.***> wrote:




Heya, the display is what is making the connection. Without that the bike will not have the Bluetooth hardware needed.

**Comment by blopker** [comment]
I'm guessing that is true, but I do not have a ZX. Maybe the info at https://www.reverse.bike/ can be helpful?

**Comment by louisber7** [comment]
Thank you for your help and looking forward to getting on your app! Thanks for all you do. 


Sent from Yahoo Mail for iPhone


On Friday, December 27, 2024, 12:24 PM, Bo Lopker ***@***.***> wrote:




I'm guessing that is true, but I do not have a ZX. Maybe the info at https://www.reverse.bike/ can be helpful?
