### ISSUE TITLE
[iOS] ModeLock doesn't reconnect while phone is off

### ISSUE THREAD

**Issue by Le-Marquis** [blopker/superduper#7]
the lock mode does not work the app is in the background and when I turn the bike on and off I have to reopen the app for the app to reconnect to the bike

hope it helps

**Comment by blopker** [comment]
This happens for me sometimes as well. I'm looking into how to make the reconnection more robust when the phone is off. Right now I can see the app is trying to reconnect, but fails to actually do so until the screen is turned back on. Thanks for confirming this is an issue with other people.

**Comment by Le-Marquis** [comment]
maybe you can use the new ios16 system of live activity to keep the app on

**Comment by blopker** [comment]
I've found a way to fix this on Android! That fix is now in production. Still looking into iOS though...

**Comment by HSprogress** [comment]
> I've found a way to fix this on Android! That fix is now in production. Still looking into iOS though...

Hi i have solved previous problem 
I have another qusetion.
The background lock. It doesn’t work. It only works when app’s screen is on. 

Did you solve the problem with ios?? 

Thank you for your service.

**Comment by blopker** [comment]
Sadly, iOS cannot support this feature due to technical limitations of the platform.
